version: "1.0"

usage_steps:
  en:
    - "1. Select a folder to scan"
    - "2. Dispatch photos to the corresponding folder based on the creation date"
    - "3. YYYY_MM_Event"
    - "4. If there are duplicate files with the same name, they will be named with an underscore and a number"
    - "5. If there is no date or the file format is not supported, the file will remain in the original folder"
    - "6. Image File Format Supported: HEIF, JPG, PNG, MOV, MP4"
  zh_tw:
    - "1. 選擇要掃描的資料夾"
    - "2. 依照照片生成日期分類"
    - "3. 依照 YYYY_MM_Event 分類"
    - "4. 如果有多個相同檔名，會用底線_01來區分"
    - "5. 如果沒有日期或不支援的格式，照片會留在原地"
    - "6. 支援的格式: HEIF, JPG, PNG, MOV, MP4"
  zh_cn:
    - "1. 选择要扫描的文件夹"
    - "2. 依照照片生成日期分類"
    - "3. 依照 YYYY_MM_Event 分類"
    - "4. 如果有多個相同檔名，會用底線_01來區分"
    - "5. 如果沒有日期或不支援的格式，照片會留在原地"
    - "6. 支援的格式: HEIF, JPG, PNG, MOV, MP4"

translations:
  en:
    window_title: "Photo Organizer"
    select_folder: "Select Folder"
    no_folder_selected: "No folder selected"
    max_depth: "Select Folder Depth:"
    generate_csv: "Generate CSV"
    generate_pdf: "Generate PDF"
    select_output: "Select Output Location"
    no_output_selected: "No output location selected"
    start_processing: "Start Organizing"
    menu_help: "Help"
    menu_usage: "Usage Guide"
    menu_about: "About"
    language: "Language"
    status_ready: "Ready to organize photos"
    status_processing: "Processing photos..."
    status_complete: "Photo organization completed!"
    status_error: "Error: {}"
    error_no_input_folder: "Please select a folder first"
    error_no_output_folder: "Error: Please select an output location"
    error_no_output_format: "Error: Please select at least one output format (CSV or PDF)"
    company_name: ""
    copyright: "Copyright © 2024 HuHu Tech."
    version_text: "Version: {}"
    select_folder_placeholder: "Click Browse to select a folder"
    browse_button: "Browse"

  zh_tw:
    window_title: "照片整理器"
    select_folder: "選擇資料夾"
    no_folder_selected: "未選擇資料夾"
    max_depth: "選擇顯示層數:"
    generate_csv: "生成 CSV"
    generate_pdf: "生成 PDF"
    select_output: "選擇輸出位置"
    no_output_selected: "未選擇輸出位置"
    start_processing: "開始整理"
    menu_help: "幫助"
    menu_usage: "使用說明"
    menu_about: "關於"
    language: "語言"
    status_ready: "準備整理照片"
    status_processing: "正在處理照片..."
    status_complete: "照片整理完成！"
    status_error: "錯誤: {}"
    error_no_input_folder: "錯誤：請選擇要掃描的資料夾"
    error_no_output_folder: "錯誤：請選擇輸出位置"
    error_no_output_format: "錯誤請至少選擇一種輸出格式(CSV 或 PDF)"
    company_name: ""
    copyright: "版權所有 © 2024 HuHu Tech"
    version_text: "版本：{}"
    select_folder_placeholder: "點擊瀏覽選擇資料夾"
    browse_button: "瀏覽"

  zh_cn:
      window_title: "照片整理器"
      select_folder: "选择文件夹"
      no_folder_selected: "未选择文件夹"
      max_depth: "选择显示层数:"
      generate_csv: "生成 CSV"
      generate_pdf: "生成 PDF"
      select_output: "选择输出位置"
      no_output_selected: "未选择输出位置"
      start_processing: "开始处理"
      menu_help: "帮助"
      menu_usage: "使用说明"
      menu_about: "关于"
      language: "语言"
      status_ready: "就绪"
      status_processing: "处理中..."
      status_complete: "完成"
      status_error: "错误: {}"
      error_no_input_folder: "错误：请选择要扫描的文件夹"
      error_no_output_folder: "错误：请选择输出位置"
      error_no_output_format: "错误：请至少选择一种输出格式（CSV 或 PDF）"
      company_name: ""
      copyright: "版权所有 © 2024 HuHu Tech"
      version_text: "版本：{}"
      select_folder_placeholder: "点击浏览选择文件夹"
      browse_button: "浏览"
